version: '3.7'

services:
  influxdb:
    build: influxdb
    restart: always
    container_name: influxdb
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    build: grafana
    restart: always
    container_name: grafana
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
